name: Sync Changes

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install server dependencies
      working-directory: ./server
      run: npm install
      
    - name: Install client dependencies
      working-directory: ./client
      run: npm install
      
    - name: Build client
      working-directory: ./client
      run: npm run build
      
    - name: Run tests
      run: |
        cd server && npm test
        cd ../client && npm test
